### PR TITLE
using reduce to transform request body

### PR DESCRIPTION
**Pull request by xtrycatchx**
minor. replacing if's with reduce

### CODE REVIEW

**Comment by melbaldove** [comment]
Hello @xtrycatchx . The reason why I went with the approach was to make explicit what fields we accept. If we merge your PR, we would be saving all fields from child objects. What do you think?

**Comment by xtrycatchx** [comment]
ok, understood. i thought was intentionally left as long if-else :) 

if my understanding is correct, we want to avoid scenarios where bodies got injected data we don't want/need? like this:
```
connectivity : {
   available: "...",
   detailedState: "..",
   injected_data: "injected value" // <--- this one?
}
```

**Comment by melbaldove** [comment]
Yes. Although if they were injecting stuff, it gets escaped in the clean method in utils.js. We want to strip unnecessary fields tho.

**Comment by melbaldove** [comment]
Also its a mapper. Concept from Clean Architecture. So the fields we are mapping from/to must be explicit.

**Comment by melbaldove** [comment]
Lets merge your other refactorings tho :)) Please create a new PR @xtrycatchx

**Pull request closed without merging**
